# Author: Jake Mathai
# Purpose: Docker compose config

version: '3'
volumes:
  uniswap-db:
services:
  db:  # DB container
    image: postgres
    container_name: db
    hostname: db
    ports:
      - '5432:5432'
    expose:
      - '5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - uniswap-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]  # Test indicating when db ready to accept connections
      interval: 5s
      timeout: 5s
      retries: 5
  uniswap:  # Data streaming container
    restart: always
    container_name: uniswap
    hostname: uniswap
    build:
      context: ./src
      dockerfile: Dockerfile
    command: ['node', 'dispatch.js']
    depends_on:
      db:
        condition: service_healthy  # Wait for db before executing
    environment:
      - ON_CHAIN=true
      - MODULE=tasks/uniswap
      - FUNCTION=uniswap
      - PROD=true
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
