version: "3"
services:
  archiver:  # Uniswap on-chain data streaming container
      restart: unless-stopped
      container_name: archiver
      build:
        context: .
        dockerfile: ./conf/Dockerfile
      command: ['node', 'dispatch.js']
      environment:
        - TASK=archiver
