version: "3"
services:
  track-pairs:  # Uniswap on-chain data streaming container
      restart: unless-stopped
      container_name: track-pairs
      build:
        context: .
        dockerfile: ./conf/Dockerfile
      command: ['node', 'dispatch.js']
      environment:
        - TASK=track-pairs
